name: Test
on:
  workflow_dispatch:
  pull_request:
    branches:
    
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install protobuf compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup Go (with module and build cache)
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Cache googleapis repo
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: googleapis
          key: ${{ runner.os }}-googleapis-cache
          restore-keys: |
            ${{ runner.os }}-googleapis-
      - name: Prepare googleapis path
        run: |
          if [ -d googleapis ]; then
            echo "Using cached googleapis"
          else
            git clone --depth 1 https://github.com/googleapis/googleapis.git googleapis
          fi
          sudo rm -rf /tmp/googleapis || true
          ln -s "$GITHUB_WORKSPACE/googleapis" /tmp/googleapis
      - name: Test
        run: ./test.sh
